server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

# MyBatis配置
mybatis:
    mapperLocations: classpath:mappers/**/*.xml
    configLocation: classpath:mybatis.xml

# 测试用
amazon:
  sourceId: "This is sourceId"

---
spring:
  profiles: dev
  thymeleaf:
          cache: false
debug: false

---
spring:
  profiles: pro
  thymeleaf:
    cache: true
debug: false